---
title: "Sample QR"
author: "Amy Crawford"
date: "2/25/2019"
output: pdf_document
geometry: "top=1cm, right=1.8cm, left=1.5cm"
header-includes:
  \AtBeginDocument{\let\maketitle\relax}
  \pagenumbering{gobble}
---
```{r, echo = F, warning=FALSE, fig.height=2, fig.width=7, results='asis'}
library(qrcode)
library(gridExtra)
library(ggplot2)
library(tidyr)
library(grid)
########################## found this online, works well - fills image box.
ggqrcode <- function(text, color="black", alpha=1) {
  pkg <- "qrcode"
  require(pkg, character.only = TRUE)
  x <- qrcode_gen(text, plotQRcode=F, dataOutput=T)
  x <- as.data.frame(x)
  
  y <- x
  y$id <- rownames(y)
  y <- gather(y, "key", "value", colnames(y)[-ncol(y)])
  y$key = factor(y$key, levels=rev(colnames(x)))
  y$id = factor(y$id, levels=rev(rownames(x)))
  
  ggplot(y, aes_(x=~id, y=~key)) + geom_tile(aes_(fill=~value), alpha=alpha) +
    scale_fill_gradient(low="white", high=color) +
    theme_void() + theme(legend.position='none')
}
```




```{r, echo = F, warning=FALSE, fig.height=1, fig.width=8, fig.align= 'right',results='asis'}
writerID <- rep(paste0("00", c(16:25)), each = 6)
promptnum <- rep(c("1", "1", "1", "2", "2", "2"), times = length(unique(writerID)))
promptrep <- rep(c("1", "2", "3"), times = length(unique(writerID))*2)
sitting <- rep("01", times = length(writerID))

labelinfo <-cbind(writerID, promptnum, promptrep, sitting)

strings <- c(); qrcode <- c()
for(i in 1:length(writerID)){
 strings[i] <- paste("Batch1", writerID[i], sitting, "Samples", paste(promptnum[i],"_", promptrep[i], sep = ""), sep = "/")
}


for(i in 1:60){
  cat("\n\n\\pagebreak\n")
  
p1 <-grid::textGrob(paste0("\n\n\n\nRepetition #", promptrep[i], "\nPrompt #",promptnum[i], "\nWID:", writerID[i]), x=0, hjust=0, gp=gpar(fontsize = 10))
p2 <- grid::textGrob("\nPlease write below the line.", x = unit(1.05, "npc"), y = unit(0.5, "npc"), hjust=0, gp=gpar(fontsize = 10, fontface="bold", just = "centre"))

# This will write "Please write below the line only on the first sample page for each writerID."
# if(i == 1 || writerID[i] != writerID[i-1]){
#   p2 <- grid::textGrob("\nPlease write below the line.", x=0, hjust=0, gp=gpar(fontsize = 10, fontface="bold"))
# }else{
#     p2 <- grid::textGrob("\n  ", x=0, hjust=0, gp=gpar(fontsize = 10, fontface="bold"))
#   }

#QR code
p3 <- ggqrcode(strings[i])

#blank element to fill space between text and QR
blank <- grid.rect(gp=gpar(col = "white"))

#plot everything
grid.arrange(arrangeGrob(p1, p2, nrow = 2), blank, arrangeGrob(p3 + coord_fixed()), ncol=3, widths = c(2,3,1))

#latex commands printed then executed
cat("\n\n\\vspace{-3mm}\n") #negative vertical space to pull the line up
cat("\n\n\\begin{center}\\rule{\\linewidth}{1pt}\\end{center}\n") #the line
cat("\n\n\\pagebreak\n")
}
```


































